name: somospie
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - gdal
  - pip
  - pip:
      - pandas
      - pyspark
      - findspark
      - scikit-learn
      - scikit-image
      - matplotlib
      - grass-session
      - bokeh==3.1.1
      - xmltodict
      - requests
      - colorcet
      - geopandas
      - tqdm
      - panel==1.3.6 
      - pyvista 
      - vtk 
      - jupyter
      # - openvisus